{
 "title": "algo1",
 "time": { "from": "2001-11-26T00:00:00.000Z", "to": "2007-11-15T00:00:00.000Z" },
 "panels": [
  {
   "title": "Algo Analysis",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "quant",
     "rawSql": "SELECT sharpe_ratio, max_drawdown, max_drawdown_dur FROM quant.analysis WHERE name = 'algo1'"
    }
   ]
  },
  {
   "title": "recorder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "quant",
     "rawSql": "SELECT timestamp, value_current FROM quant.recorder"
    }
   ]
  },
  {
   "title": "Asset Value",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "quant",
     "rawSql": "SELECT timestamp, open, close, low, high FROM quant.algo1"
    }
   ]
  }
 ]
}