services:
  quantDatabase:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_DATABASE: quant
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
#     volumes:
#       - quant-db:/var/lib/mysql
# volumes :
#   quant-db: